### ISSUE TITLE
Created bullet_client with id...

### ISSUE THREAD

**Issue by lgvaz** [benelot/pybullet-gym#13]
Every time we reset a environment that is a subclass from `MJCFBasedRobot` we get the message "Created bullet_client with id=0".

Am I doing something wrong? This message becomes annoying really fast.

**Comment by benelot** [comment]
In case it does not break your code, then it might be expected behaviour. I
depend on OpenGL and physics engine of bullet, for python pybullet, which
probably drops this message. If you find it annoying, you could (or I
could) report this to the github.com/...bullet repository's issues. Just
tell me how you proceed.

**Comment by lgvaz** [comment]
Actually this is being printed by [here](https://github.com/benelot/pybullet-gym/blob/master/pybulletgym/envs/roboschool/robot_bases.py#L111) and [here](https://github.com/benelot/pybullet-gym/blob/master/pybulletgym/envs/mujoco/robot_bases.py#L111).
