### ISSUE TITLE
Why are all the free joints in the asset xml files commented out?

### ISSUE THREAD

**Issue by knn1989** [benelot/pybullet-gym#26]
I notice in all the asset xml files, the free joints are commented out.

For example, in the ant.xml line 14 is commented out.
""

What is the reason for this? 

Is there any way to reproduce the same effect as using free joint i.e free joint has 6DOF (3 translational and 3 rotational degrees of freedom).

To be more specific, I want to rotate the object but cannot find a way to do so without using free joints.

**Comment by benelot** [comment]
There is a reason in pybullet why they do not use free joints at all. It is
basically no joint at all in the bullet physics engine, that is probably
why. Just try your file with a commented free joint, it should work out of
the box. Otherwise, maybe you can provide a simple example that does not
work and we can work it out. Do you need 6 DoF rotation and translation?

**Comment by benelot** [comment]
I will close this as it is an older issue. Please feel free to reopen it.
