### ISSUE TITLE
Variable 'done' returns an array of two boolean values.

### ISSUE THREAD

**Issue by BryanBo-Cao** [benelot/pybullet-gym#43]
https://github.com/benelot/pybullet-gym/blob/79396fccc1d0e170a092b50137148da48ee2edab/pybulletgym/envs/mujoco/envs/pendulum/inverted_pendulum_env.py#L32

Variable 'done' returns an array of two boolean values.

Credit to Xiang Li.

**Comment by pierre-si** [comment]
The reason why "done" returns an array instead of a boolean value is that there is a missing call to ravel() in inverted_pendulum.py. "state" should be 1D array not a 2D array.
https://github.com/benelot/pybullet-gym/blob/79396fccc1d0e170a092b50137148da48ee2edab/pybulletgym/envs/mujoco/robots/pendula/inverted_pendulum.py#L50-L52
See #47

**Comment by benelot** [comment]
Somebody made a pull request and fixed this. Thanks for reporting!
